spring:
  application:
    name: blockchainWallet-serviceCenter

server:
  port: 9010

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.8.47:${server.port}/eureka/
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#    hostname: ${spring.cloud.client.ipAddress}